### ISSUE TITLE
Support for req.body

### ISSUE THREAD

**Issue by sfali23** [types/npm-express#5]
The Request interface doesn't seem to support for req.body, DT `express-serve-static-core` seems to have req.body support.

Regards,

Farhan

**Comment by felixfbecker** [comment]
Yes, that is by design. Express itself doesn't set `req.body`. If you use express without any middleware, `req.body` will be `undefined`. What sets `req.body` is the body-parser middleware. The typings for body-parser include interfaces for parsed bodies that can be combined with the `Request` interface to explicitly state that you have used the body-parser middleware and `body` will be available as a specific type.

https://github.com/types/npm-body-parser

``` ts
import express = require('express');
import {Request, Response} from 'express';
import {text, ParsedAsText} from 'body-parser';

const app = express();

app.post('/textdemo', text({limit: '1MB'}), (req: Request & ParsedAsText, res: Response) => {
    // req.body is now a string
    console.log(req.body.substr(3));
});
```

**Comment by AlexZeitler** [comment]
Is this still the way to go?
I tried to install `@types/body-parser` and I got installed this one: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/body-parser which has no `ParsedAsJson` exported for example.
